export const navigation = [
  {
    name: "Home",
    href: "home",
  },
  {
    name: "Design Your Card",
    href: "customization",
  },
  {
    name: "Shop",
    href: "shop",
  },

  {
    name: "Compatible Phones",
    href: "compatible-phones",
  },
  {
    name: "Contact",
    href: "contact",
  },
  {
    name: "Profile Login",
    href: "login",
  },
  {
    name: "Sign Up",
    href: "signup",
  },
];

export const hero = {
  heading: "YOUR RELIABLE BUSINESS PARTNER",
  title: "Transforming Professional Networking, The Evolution of Business Cards",
  subtitle:
    "Effortlessly share your contact info, images, and videos with just one tap. Embrace sustainable networking and make every connection impactful!",
  buttonText: "CREATE YOUR CARD",
};


export const features = {
  title: "Leave a lasting impact with a distinctive, budget-friendly design.",
  subtitle:
    "Our expert team will carefully craft your card to flawlessly capture your vision and personal style.",
  buttonText: "COLLABORATE WITH DESIGNER",
};

export const design = {
  title: "Design Your Card",
  price: "$99.00",
  subtitle:
    "Next Tap provides a cutting-edge approach to connecting individuals and businesses. Using NFC business cards, share your details, images, and videos instantly with a simple tap or scan. Explore endless opportunities and revolutionize your networking today!",
  buttonText: "CREATE YOUR CARD",
};

export const newsletter = {
  title: "Get more discount Off your order",
  subtitle: "Join our mailing list",
  placeholder: "Your email address",
  buttonText: "Shop Now",
};
export const questions = [
  {
    question: "What are Next Tap NFC business cards?",
    answer:
      "Next Tap NFC business cards are smart, digital alternatives to traditional business cards. They use NFC (Near Field Communication) technology to instantly share your contact information, social media profiles, and multimedia with a simple tap or scan.",
  },
  {
    question: "How do Next Tap NFC business cards work?",
    answer:
      "Next Tap NFC business cards contain a small NFC chip that stores your information. When tapped against a compatible smartphone, it transfers your contact details, media, and more directly to the recipient's device without the need for any apps.",
  },
  {
    question: "How do I customize my Next Tap card?",
    answer:
      "Customizing your Next Tap card is simple. Just choose a design, add your personal details, and select any images or videos you want to share. Our team will craft the card to perfectly represent your brand and style.",
  },
  {
    question: "What are the benefits of using Next Tap NFC cards?",
    answer:
      "Next Tap NFC cards offer a quick and eco-friendly way to share contact details, media, and more with just a single tap, making your networking experience seamless and modern.",
  },
  {
    question: "Can I update my information on the Next Tap NFC card?",
    answer:
      "Yes, you can easily update your information on the Next Tap card without needing to print new ones, ensuring your details are always current.",
  },
  {
    question: "Are Next Tap NFC cards compatible with all devices?",
    answer:
      "Next Tap NFC cards are compatible with most modern smartphones and devices, allowing you to connect with anyone, anywhere with ease.",
  },
];

export const formQuestions = [
  {
    title: "Description",
    description: "hello",
  },
  {
    title: "Compatibility",
    description: "hello",
  },
  {
    title: "Shipping & Returns",
    description: "hello",
  },
];

export const cards = [
  {
    image: "src/assets/shopImg2.svg",
    title: "NFC Business Card - Premium Edition",
    price: "$129",
    id: 2,
    color: "black",
    rating: 4.7,
    noOfRatings: 98,
  },
  {
    image: "src/assets/shopImg3.svg",
    title: "NFC Business Card - Executive Edition",
    price: "$149",
    id: 3,
    color: "white",
    rating: 4.9,
    noOfRatings: 150,
  },
  {
    image: "src/assets/shopImg4.svg",
    title: "NFC Business Card - Luxury Edition",
    price: "$199",
    id: 4,
    color: "black",
    rating: 4.8,
    noOfRatings: 75,
  },
  {
    image: "src/assets/shopImg5.svg",
    title: "NFC Business Card - Custom Edition",
    price: "$179",
    id: 5,
    color: "white",
    rating: 4.6,
    noOfRatings: 60,
  },
  {
    image: "src/assets/shopImg2.svg",
    title: "NFC Business Card - Premium Edition",
    price: "$129",
    id: 2,
    color: "white",
    rating: 4.7,
    noOfRatings: 90,
  },
  {
    image: "src/assets/shopImg3.svg",
    title: "NFC Business Card - Executive Edition",
    price: "$149",
    id: 3,
    color: "black",
    rating: 4.8,
    noOfRatings: 110,
  },
  {
    image: "src/assets/shopImg4.svg",
    title: "NFC Business Card - Luxury Edition",
    price: "$199",
    id: 4,
    color: "white",
    rating: 4.9,
    noOfRatings: 85,
  },
  {
    image: "src/assets/shopImg5.svg",
    title: "NFC Business Card - Custom Edition",
    price: "$179",
    id: 5,
    color: "black",
    rating: 4.4,
    noOfRatings: 70,
  },
  {
    image: "src/assets/shopImg2.svg",
    title: "NFC Business Card - Premium Edition",
    price: "$129",
    id: 2,
    color: "black",
    rating: 4.6,
    noOfRatings: 95,
  },
  {
    image: "src/assets/shopImg3.svg",
    title: "NFC Business Card - Executive Edition",
    price: "$149",
    id: 3,
    color: "white",
    rating: 4.7,
    noOfRatings: 130,
  },
  {
    image: "src/assets/shopImg4.svg",
    title: "NFC Business Card - Luxury Edition",
    price: "$199",
    id: 4,
    color: "black",
    rating: 4.9,
    noOfRatings: 100,
  },
  {
    image: "src/assets/shopImg5.svg",
    title: "NFC Business Card - Custom Edition",
    price: "$179",
    id: 5,
    color: "white",
    rating: 4.5,
    noOfRatings: 80,
  },
  {
    image: "src/assets/shopImg2.svg",
    title: "NFC Business Card - Premium Edition",
    price: "$129",
    id: 2,
    color: "white",
    rating: 4.7,
    noOfRatings: 97,
  },
  {
    image: "src/assets/shopImg3.svg",
    title: "NFC Business Card - Executive Edition",
    price: "$149",
    id: 3,
    color: "black",
    rating: 4.8,
    noOfRatings: 120,
  },
  {
    image: "src/assets/shopImg4.svg",
    title: "NFC Business Card - Luxury Edition",
    price: "$199",
    id: 4,
    color: "white",
    rating: 4.9,
    noOfRatings: 105,
  },
  {
    image: "src/assets/shopImg5.svg",
    title: "NFC Business Card - Custom Edition",
    price: "$179",
    id: 5,
    color: "black",
    rating: 4.5,
    noOfRatings: 75,
  },
  {
    image: "src/assets/shopImg2.svg",
    title: "NFC Business Card - Premium Edition",
    price: "$129",
    id: 2,
    color: "black",
    rating: 4.6,
    noOfRatings: 100,
  },
  {
    image: "src/assets/shopImg3.svg",
    title: "NFC Business Card - Executive Edition",
    price: "$149",
    id: 3,
    color: "white",
    rating: 4.8,
    noOfRatings: 135,
  },
  {
    image: "src/assets/shopImg4.svg",
    title: "NFC Business Card - Luxury Edition",
    price: "$199",
    id: 4,
    color: "black",
    rating: 4.9,
    noOfRatings: 110,
  },
  {
    image: "src/assets/shopImg5.svg",
    title: "NFC Business Card - Custom Edition",
    price: "$179",
    id: 5,
    color: "white",
    rating: 4.7,
    noOfRatings: 90,
  },
];


export const compatiblePhonesData = [
  { brand: "Acer", model: "CloudMobile S500", os: "Android" },
  { brand: "Acer", model: "Liquid E1", os: "Android" },
  { brand: "Acer", model: "Liquid S2", os: "Android" },
  { brand: "Alcatel", model: "1x", os: "Android" },
  { brand: "Alcatel", model: "3", os: "Android" },
  { brand: "Alcatel", model: "5", os: "Android" },
  { brand: "Alcatel", model: "5V", os: "Android" },
  { brand: "Alcatel", model: "A7", os: "Android" },
  { brand: "Alcatel", model: "Idol 3", os: "Android" },
  { brand: "Apple", model: "iPhone 7", os: "iOS 11" },
  { brand: "Apple", model: "iPhone 8", os: "iOS 11" },
  { brand: "Apple", model: "iPhone X", os: "iOS 11" },
  { brand: "Apple", model: "iPhone Xs", os: "iOS" },
  { brand: "Apple", model: "iPhone Xs Max", os: "iOS" },
  { brand: "Apple", model: "iPhone Xr", os: "iOS" },
  { brand: "Asus", model: "Padfone 2", os: "Android" },
  { brand: "Asus", model: "Padfone Infinity", os: "Android" },
  { brand: "Asus", model: "ROG Phone", os: "Android" },
  { brand: "Asus", model: "Zenfone 2", os: "Android" },
  { brand: "Asus", model: "Zenfone 5", os: "Android" },
  { brand: "Asus", model: "Zenfone 5 Lite", os: "Android" },
  { brand: "Asus", model: "Zenfone 5Z", os: "Android" },
  { brand: "Blackberry", model: "Bold 9900", os: "Blackberry OS" },
  { brand: "Blackberry", model: "Bold 9930", os: "Blackberry OS" },
  { brand: "Blackberry", model: "Classic", os: "Blackberry 10" },
  { brand: "Blackberry", model: "Curve 9350", os: "Blackberry OS" },
  { brand: "Blackberry", model: "Curve 9360", os: "Blackberry OS" },
  { brand: "Blackberry", model: "Curve 9370", os: "Blackberry OS" },
  { brand: "Blackberry", model: "Curve 9380", os: "Blackberry OS" },
  { brand: "Blackberry", model: "Key2 LE", os: "Android" },
  { brand: "Blackberry", model: "KEYone", os: "Android" },
  { brand: "Blackberry", model: "P’9982 Porsche Design", os: "Blackberry 10" },
  { brand: "Blackberry", model: "P’9983", os: "Blackberry 10" },
  { brand: "Blackberry", model: "Q10", os: "Blackberry 10" },
  { brand: "Blackberry", model: "Q5", os: "Blackberry 10" },
  { brand: "Blackberry", model: "Z10", os: "Blackberry 10" },
  { brand: "Blackberry", model: "Z30", os: "Blackberry 10" },
  { brand: "Dell", model: "Venue 8 Pro 5830", os: "Windows 8.1" },
  { brand: "Fujitsu", model: "Arrows A 301F", os: "Android" },
  { brand: "Fujitsu", model: "Arrows NX F-01F", os: "Android" },
  { brand: "Fujitsu", model: "Arrows NX F-05F", os: "Android" },
  { brand: "Fujitsu", model: "Arrows NX F-06E", os: "Android" },
  { brand: "Fujitsu", model: "Arrows S eM01F", os: "Android" },
  { brand: "Fujitsu", model: "Arrows V F-04E", os: "Android" },
  { brand: "Google", model: "Galaxy Nexus", os: "Android" },
  { brand: "Google", model: "Nexus 10", os: "Android" },
  { brand: "Google", model: "Nexus 4", os: "Android" },
  { brand: "Google", model: "Nexus 5", os: "Android" },
  { brand: "Google", model: "Nexus 5X", os: "Android" },
  { brand: "Google", model: "Nexus 6", os: "Android" },
  { brand: "Google", model: "Nexus 6P", os: "Android" },
  { brand: "Google", model: "Nexus 7 (2013)", os: "Android" },
  { brand: "Google", model: "Nexus 7 (2012)", os: "Android" },
  { brand: "Google", model: "Nexus 9", os: "Android" },
  { brand: "Google", model: "Nexus S", os: "Android" },
  { brand: "Google", model: "Pixel", os: "Android" },
  { brand: "Google", model: "Pixel XL", os: "Android" },
  { brand: "Google", model: "Pixel 2", os: "Android" },
  { brand: "Google", model: "Pixel 2 XL", os: "Android" },
  { brand: "Google", model: "Pixel 3", os: "Android" },
  { brand: "Google", model: "Pixel 3 XL", os: "Android" },
  { brand: "Honor", model: "8 Pro", os: "Android" },
  { brand: "Honor", model: "9", os: "Android" },
  { brand: "Honor", model: "Magic", os: "Android" },
  { brand: "Honor", model: "Magic 2", os: "Android" },
  { brand: "Honor", model: "Note 10", os: "Android" },
  { brand: "Honor", model: "V9", os: "Android" },
  { brand: "Honor", model: "View 20", os: "Android" },
  { brand: "HTC", model: "8X", os: "Windows Phone" },
  { brand: "HTC", model: "10", os: "Android" },
  { brand: "HTC", model: "10 Evo", os: "Android" },
  { brand: "HTC", model: "Amaze 4G", os: "Android" },
  { brand: "HTC", model: "Desire 12s", os: "Android" },
  { brand: "HTC", model: "Desire 530", os: "Android" },
  { brand: "HTC", model: "Desire 610", os: "Android" },
  { brand: "HTC", model: "Desire 620", os: "Android" },
  { brand: "HTC", model: "Desire 620G", os: "Android" },
  { brand: "HTC", model: "Desire 816", os: "Android" },
  { brand: "HTC", model: "Desire 820", os: "Android" },
  { brand: "HTC", model: "Desire C", os: "Android" },
  { brand: "HTC", model: "Desire Eye", os: "Android" },
  { brand: "HTC", model: "Evo 4G LTE", os: "Android" },
  { brand: "HTC", model: "First", os: "Android" },
  { brand: "HTC", model: "J Butterfly", os: "Android" },
  { brand: "HTC", model: "One", os: "Android" },
  { brand: "HTC", model: "One A9", os: "Android" },
  { brand: "HTC", model: "One M8", os: "Android" },
  { brand: "HTC", model: "One M8 for Windows", os: "Windows Phone" },
  { brand: "HTC", model: "One M9", os: "Android" },
  { brand: "HTC", model: "One M9+", os: "Android" },
  { brand: "HTC", model: "One Max", os: "Android" },
  { brand: "HTC", model: "One Mini 2", os: "Android" },
  { brand: "HTC", model: "One SV", os: "Android" },
  { brand: "HTC", model: "One VX", os: "Android" },
  { brand: "HTC", model: "One X", os: "Android" },
  { brand: "HTC", model: "One X+", os: "Android" },
  { brand: "HTC", model: "One X10", os: "Android" },
  { brand: "HTC", model: "One XL", os: "Android" },
  { brand: "HTC", model: "U11", os: "Android" },
  { brand: "HTC", model: "U11 EYEs", os: "Android" },
  { brand: "HTC", model: "U11 Life", os: "Android" },
  { brand: "HTC", model: "U11 Plus", os: "Android" },
  { brand: "HTC", model: "U12 Life", os: "Android" },
  { brand: "HTC", model: "U12 Plus", os: "Android" },
  { brand: "Huawei", model: "Ascend G6", os: "Android" },
  { brand: "Huawei", model: "Ascend Mate 7", os: "Android" },
  { brand: "Huawei", model: "Ascend P2", os: "Android" },
  { brand: "Huawei", model: "Ascend P7", os: "Android" },
  { brand: "Huawei", model: "Ascend W1", os: "Windows Phone" },
  { brand: "Huawei", model: "G8", os: "Android" },
  { brand: "Huawei", model: "Mate 9", os: "Android" },
  { brand: "Huawei", model: "Mate 10", os: "Android" },
  { brand: "Huawei", model: "Mate 10 Pro", os: "Android" },
  { brand: "Huawei", model: "Mate 20", os: "Android" },
  { brand: "Huawei", model: "Mate 20 X", os: "Android" },
  { brand: "Huawei", model: "Mate S", os: "Android" },
  { brand: "Huawei", model: "Nexus 6P", os: "Android" },
  { brand: "Huawei", model: "Nova Young", os: "Android" },
  { brand: "Huawei", model: "P smart", os: "Android" },
  { brand: "Huawei", model: "P Smart Plus", os: "Android" },
  { brand: "Huawei", model: "P8", os: "Android" },
  { brand: "Huawei", model: "P8 Lite 2017", os: "Android" },
  { brand: "Huawei", model: "P9", os: "Android" },
  { brand: "Huawei", model: "P9 Plus", os: "Android" },
  { brand: "Huawei", model: "P10", os: "Android" },
  { brand: "Huawei", model: "P10 Lite", os: "Android" },
  { brand: "Huawei", model: "P10 Plus", os: "Android" },
  { brand: "Huawei", model: "P20", os: "Android" },
  { brand: "Huawei", model: "P20 Pro", os: "Android" },
  { brand: "Huawei", model: "Watch 2", os: "Android" },
  { brand: "Intel", model: "AZ210", os: "Android" },
  { brand: "Jolla", model: "Jolla", os: "Sailfish OS" },
  { brand: "Kapsys", model: "SmartConnect", os: "Android" },
  { brand: "Kapsys", model: "SmartVision", os: "Android" },
  { brand: "Kapsys", model: "SmartVision Lite", os: "Android" },
  { brand: "Komu", model: "K8 4G", os: "Android" },
  { brand: "Lenovo", model: "P2", os: "Android" },
  { brand: "Lenovo", model: "ThinkPad X1 Carbon", os: "Windows 10" },
  { brand: "Lenovo", model: "ThinkPad X1 Yoga", os: "Windows 10" },
  { brand: "Lenovo", model: "ThinkPad X380 Yoga", os: "Windows 10" },
  { brand: "LG", model: "Escape", os: "Android" },
  { brand: "LG", model: "G Flex 2", os: "Android" },
  { brand: "LG", model: "G2", os: "Android" },
  { brand: "LG", model: "G2 Mini LTE", os: "Android" },
  { brand: "LG", model: "G3 D855", os: "Android" },
  { brand: "LG", model: "G3 S", os: "Android" },
  { brand: "LG", model: "G4 (H815)", os: "Android" },
  { brand: "LG", model: "G5", os: "Android" },
  { brand: "LG", model: "G6 (H870)", os: "Android" },
  { brand: "LG", model: "G7 Fit", os: "Android" },
  { brand: "LG", model: "G7 One", os: "Android" },
  { brand: "LG", model: "K10", os: "Android" },
  { brand: "LG", model: "K10 2018", os: "Android" },
  { brand: "LG", model: "K10 Alpha 2018", os: "Android" },
  { brand: "LG", model: "K10 Plus 2018", os: "Android" },
  { brand: "LG", model: "L Fino", os: "Android" },
  { brand: "LG", model: "L50", os: "Android" },
  { brand: "LG", model: "Nexus 5X", os: "Android" },
  { brand: "LG", model: "Optimus 4X HD", os: "Android" },
  { brand: "LG", model: "Optimus L5", os: "Android" },
  { brand: "LG", model: "Optimus L5 II", os: "Android" },
  { brand: "LG", model: "Optimus L7 II", os: "Android" },
  { brand: "LG", model: "Optimus L9 II", os: "Android" },
  { brand: "LG", model: "Optimus Vu 2", os: "Android" },
  { brand: "LG", model: "Power X", os: "Android" },
  { brand: "LG", model: "Prada 3.0", os: "Android" },
  { brand: "LG", model: "Q Stylus", os: "Android" },
  { brand: "LG", model: "Q6", os: "Android" },
  { brand: "LG", model: "Q6 Alpha", os: "Android" },
  { brand: "LG", model: "Q6 Plus", os: "Android" },
  { brand: "LG", model: "Q7", os: "Android" },
  { brand: "LG", model: "Q7 Alpha", os: "Android" },
  { brand: "LG", model: "Q7 Plus", os: "Android" },
  { brand: "LG", model: "Q8", os: "Android" },
  { brand: "LG", model: "Q9", os: "Android" },
  { brand: "LG", model: "Spectrum 2", os: "Android" },
  { brand: "LG", model: "V10", os: "Android" },
  { brand: "LG", model: "V30", os: "Android" },
  { brand: "LG", model: "V30 ThinQ", os: "Android" },
  { brand: "LG", model: "V35 ThinQ", os: "Android" },
  { brand: "LG", model: "V40 ThinQ", os: "Android" },
  { brand: "LG", model: "X venture", os: "Android" },
  { brand: "Microsoft", model: "Lumia 640XL", os: "Windows Phone" },
  { brand: "Microsoft", model: "Lumia 650", os: "Windows 10 Mobile" },
  { brand: "Microsoft", model: "Lumia 950", os: "Windows 10 Mobile" },
  { brand: "Microsoft", model: "Lumia 950XL", os: "Windows 10 Mobile" },
  { brand: "Microsoft", model: "Surface Go", os: "Windows 10" },
  { brand: "Motorola", model: "Droid Razr i", os: "Android" },
  { brand: "Motorola", model: "Droid Razr Maxx", os: "Android" },
  { brand: "Motorola", model: "Droid Razr Maxx HD", os: "Android" },
  { brand: "Motorola", model: "Moto E4", os: "Android" },
  { brand: "Motorola", model: "Moto E4 Plus", os: "Android" },
  { brand: "Motorola", model: "Moto G 2014", os: "Android" },
  { brand: "Motorola", model: "Moto G5S Plus", os: "Android" },
  { brand: "Motorola", model: "Moto Maxx", os: "Android" },
  { brand: "Motorola", model: "Moto x", os: "Android" },
  { brand: "Motorola", model: "Moto X Play", os: "Android" },
  { brand: "Motorola", model: "Moto Z2 Force", os: "Android" },
  { brand: "Motorola", model: "Moto Z2 Play", os: "Android" },
  { brand: "Motorola", model: "Moto Z3 Play Power Edition", os: "Android" },
  { brand: "Motorola", model: "Photon Q", os: "Android" },
  { brand: "Nokia", model: "3", os: "Android" },
  { brand: "Nokia", model: "5", os: "Android" },
  { brand: "Nokia", model: "5.1", os: "Android" },
  { brand: "Nokia", model: "7 Plus", os: "Android" },
  { brand: "Nokia", model: "8", os: "Android" },
  { brand: "Nokia", model: "603", os: "Symbian" },
  { brand: "Nokia", model: "6131", os: "Nokia OS" },
  { brand: "Nokia", model: "6212 Classic", os: "Nokia OS" },
  { brand: "Nokia", model: "6216 Classic", os: "Nokia OS" },
  { brand: "Nokia", model: "700", os: "Symbian" },
  { brand: "Nokia", model: "701", os: "Symbian" },
  { brand: "Nokia", model: "808 PureView", os: "Symbian" },
  { brand: "Nokia", model: "C7", os: "Symbian" },
  { brand: "Nokia", model: "Lumia 1020", os: "Windows Phone" },
  { brand: "Nokia", model: "Lumia 1520", os: "Windows Phone" },
  { brand: "Nokia", model: "Lumia 2520", os: "Windows Phone" },
  { brand: "Nokia", model: "Lumia 720", os: "Windows Phone" },
  { brand: "Nokia", model: "Lumia 730", os: "Windows Phone" },
  { brand: "Nokia", model: "Lumia 735", os: "Windows Phone" },
  { brand: "Nokia", model: "Lumia 810", os: "Windows Phone" },
  { brand: "Nokia", model: "Lumia 820", os: "Windows Phone" },
  { brand: "Nokia", model: "Lumia 822", os: "Windows Phone" },
  { brand: "Nokia", model: "Lumia 830", os: "Windows Phone" },
  { brand: "Nokia", model: "Lumia 920", os: "Windows Phone" },
  { brand: "Nokia", model: "Lumia 925", os: "Windows Phone" },
  { brand: "Nokia", model: "Lumia 928", os: "Windows Phone" },
  { brand: "Nokia", model: "Lumia 930", os: "Windows Phone" },
  { brand: "Nokia", model: "Lumia Icon", os: "Windows Phone" },
  { brand: "Nokia", model: "N9", os: "MeeGo" },
  { brand: "OnePlus", model: "One", os: "Android" },
  { brand: "OnePlus", model: "3", os: "Android" },
  { brand: "OnePlus", model: "3T", os: "Android" },
  { brand: "OnePlus", model: "5", os: "Android" },
  { brand: "OnePlus", model: "5T", os: "Android" },
  { brand: "OnePlus", model: "6", os: "Android" },
  { brand: "OnePlus", model: "6T", os: "Android" },
  { brand: "Oppo", model: "Find X", os: "Android" },
  { brand: "Oppo", model: "N3", os: "Android" },
  { brand: "Oppo", model: "RX17 Pro", os: "Android" },
  { brand: "RugGear", model: "RG500", os: "Android" },
  { brand: "RugGear", model: "RG700", os: "Android" },
  { brand: "RugGear", model: "RG900", os: "Android" },
  { brand: "Samsung", model: "Ativ S", os: "Windows Phone" },
  { brand: "Samsung", model: "Galaxy A3 2017", os: "Android 8.0" },
  { brand: "Samsung", model: "Galaxy A5 2017", os: "Android 8.0" },
  { brand: "Samsung", model: "Galaxy A7", os: "Android" },
  { brand: "Samsung", model: "Galaxy A7 2018", os: "Android" },
  { brand: "Samsung", model: "Galaxy A8", os: "Android" },
  { brand: "Samsung", model: "Galaxy A8 2018", os: "Android" },
  { brand: "Samsung", model: "Galaxy A8 Plus 2018", os: "Android" },
  { brand: "Samsung", model: "Galaxy A8s", os: "Android" },
  { brand: "Samsung", model: "Galaxy Ace 3", os: "Android" },
  { brand: "Samsung", model: "Galaxy Ace 4", os: "Android" },
  { brand: "Samsung", model: "Galaxy Alpha", os: "Android" },
  { brand: "Samsung", model: "Galaxy Core 2", os: "Android" },
  { brand: "Samsung", model: "Galaxy Core Advance", os: "Android" },
  { brand: "Samsung", model: "Galaxy Core Plus", os: "Android" },
  { brand: "Samsung", model: "Galaxy Core Prime", os: "Android" },
  { brand: "Samsung", model: "Galaxy Express 2", os: "Android" },
  { brand: "Samsung", model: "Galaxy Fame", os: "Android" },
  { brand: "Samsung", model: "Galaxy Fame Lite", os: "Android" },
  { brand: "Samsung", model: "Galaxy Grand Duos", os: "Android" },
  { brand: "Samsung", model: "Galaxy Grand Prime", os: "Android" },
  { brand: "Samsung", model: "Galaxy J3 (2016)", os: "Android" },
  { brand: "Samsung", model: "Galaxy J4 Plus", os: "Android" },
  { brand: "Samsung", model: "Galaxy J5 (2016)", os: "Android" },
  { brand: "Samsung", model: "Galaxy J5 (2017)", os: "Android" },
  { brand: "Samsung", model: "Galaxy J5 Pro", os: "Android" },
  { brand: "Samsung", model: "Galaxy J6 Plus", os: "Android" },
  { brand: "Samsung", model: "Galaxy J7 (2017)", os: "Android" },
  { brand: "Samsung", model: "Galaxy K Zoom", os: "Android" },
  { brand: "Samsung", model: "Galaxy Mega", os: "Android" },
  { brand: "Samsung", model: "Galaxy Mini 2", os: "Android" },
  { brand: "Samsung", model: "Galaxy Nexus", os: "Android" },
  { brand: "Samsung", model: "Galaxy Note 2", os: "Android" },
  { brand: "Samsung", model: "Galaxy Note 3", os: "Android" },
  { brand: "Samsung", model: "Galaxy Note 3 Neo", os: "Android" },
  { brand: "Samsung", model: "Galaxy Note 4", os: "Android" },
  { brand: "Samsung", model: "Galaxy Note 5", os: "Android" },
  { brand: "Samsung", model: "Galaxy Note 7", os: "Android" },
  { brand: "Samsung", model: "Galaxy Note 7 FE", os: "Android" },
  { brand: "Samsung", model: "Galaxy Note 8", os: "Android" },
  { brand: "Samsung", model: "Galaxy Note Edge", os: "Android" },
  { brand: "Samsung", model: "Galaxy S3", os: "Android" },
  { brand: "Samsung", model: "Galaxy S3 Neo", os: "Android" },
  { brand: "Samsung", model: "Galaxy S4", os: "Android" },
  { brand: "Samsung", model: "Galaxy S4 Active", os: "Android" },
  { brand: "Samsung", model: "Galaxy S4 Mini", os: "Android" },
  { brand: "Samsung", model: "Galaxy S4 zoom", os: "Android" },
  { brand: "Samsung", model: "Galaxy S5", os: "Android" },
  { brand: "Samsung", model: "Galaxy S5 Mini", os: "Android" },
  { brand: "Samsung", model: "Galaxy S6", os: "Android" },
  { brand: "Samsung", model: "Galaxy S6 Edge", os: "Android" },
  { brand: "Samsung", model: "Galaxy S6 Edge Plus", os: "Android" },
  { brand: "Samsung", model: "Galaxy S7", os: "Android 8" },
  { brand: "Samsung", model: "Galaxy S7 Edge", os: "Android" },
  { brand: "Samsung", model: "Galaxy S8", os: "Android 8" },
  { brand: "Samsung", model: "Galaxy S8+", os: "Android" },
  { brand: "Samsung", model: "Galaxy S9", os: "Android" },
  { brand: "Samsung", model: "Galaxy S9 Plus", os: "Android" },
  { brand: "Samsung", model: "Galaxy Superior", os: "Android" },
  { brand: "Samsung", model: "Galaxy Tab Active", os: "Android" },
  { brand: "Samsung", model: "Galaxy Tab Active2", os: "Android" },
  { brand: "Samsung", model: "Galaxy Xcover 3 (G388F)", os: "Android" },
  { brand: "Samsung", model: "Galaxy Xcover 3 (G389F)", os: "Android" },
  { brand: "Samsung", model: "Galaxy Xcover 4", os: "Android" },
  { brand: "Samsung", model: "Galaxy Young", os: "Android" },
  { brand: "Samsung", model: "W2019", os: "Android" },
  { brand: "Samsung", model: "Wave 578", os: "Bada" },
  { brand: "Sharp", model: "Aquos D10", os: "Android" },
  { brand: "Sony", model: "SmartWatch 2", os: "Android" },
  { brand: "Sony", model: "Xperia Acro S", os: "Android" },
  { brand: "Sony", model: "Xperia C4", os: "Android" },
  { brand: "Sony", model: "Xperia C5 Ultra", os: "Android" },
  { brand: "Sony", model: "Xperia Ion", os: "Android" },
  { brand: "Sony", model: "Xperia L", os: "Android" },
  { brand: "Sony", model: "Xperia L2", os: "Android" },
  { brand: "Sony", model: "Xperia M", os: "Android" },
  { brand: "Sony", model: "Xperia M Dual", os: "Android" },
  { brand: "Sony", model: "Xperia M2", os: "Android" },
  { brand: "Sony", model: "Xperia M2 Aqua", os: "Android" },
  { brand: "Sony", model: "Xperia M4 Aqua", os: "Android" },
  { brand: "Sony", model: "Xperia M5", os: "Android" },
  { brand: "Sony", model: "Xperia P", os: "Android" },
  { brand: "Sony", model: "Xperia S", os: "Android" },
  { brand: "Sony", model: "Xperia SL", os: "Android" },
  { brand: "Sony", model: "Xperia Sola", os: "Android" },
  { brand: "Sony", model: "Xperia SP", os: "Android" },
  { brand: "Sony", model: "Xperia T", os: "Android" },
  { brand: "Sony", model: "Xperia T3", os: "Android" },
  { brand: "Sony", model: "Xperia Tablet Z", os: "Android" },
  { brand: "Sony", model: "Xperia TX", os: "Android" },
  { brand: "Sony", model: "Xperia V", os: "Android" },
  { brand: "Sony", model: "Xperia X", os: "Android" },
  { brand: "Sony", model: "Xperia X Compact", os: "Android" },
  { brand: "Sony", model: "Xperia X Performance", os: "Android" },
  { brand: "Sony", model: "Xperia XA1 Plus", os: "Android" },
  { brand: "Sony", model: "Xperia XA1 Ultra", os: "Android" },
  { brand: "Sony", model: "Xperia XA2", os: "Android" },
  { brand: "Sony", model: "Xperia XA2 Plus", os: "Android" },
  { brand: "Sony", model: "Xperia XA2 Ultra", os: "Android" },
  { brand: "Sony", model: "Xperia XZ", os: "Android" },
  { brand: "Sony", model: "Xperia XZ Premium", os: "Android" },
  { brand: "Sony", model: "Xperia XZ1", os: "Android" },
  { brand: "Sony", model: "Xperia XZ1 Compact", os: "Android" },
  { brand: "Sony", model: "Xperia Z", os: "Android" },
  { brand: "Sony", model: "Xperia Z Ultra", os: "Android" },
  { brand: "Sony", model: "Xperia Z1", os: "Android" },
  { brand: "Sony", model: "Xperia Z1 Compact", os: "Android" },
  { brand: "Sony", model: "Xperia Z2", os: "Android" },
  { brand: "Sony", model: "Xperia Z2 Tablet", os: "Android" },
  { brand: "Sony", model: "Xperia Z3", os: "Android" },
  { brand: "Sony", model: "Xperia Z3 Compact", os: "Android" },
  { brand: "Sony", model: "Xperia Z3+", os: "Android" },
  { brand: "Sony", model: "Xperia Z4 Tablet", os: "Android" },
  { brand: "Sony", model: "Xperia Z5 Compact", os: "Android" },
  { brand: "Sony", model: "Xperia Z5 Premium", os: "Android" },
  { brand: "Sony", model: "Xperia ZL", os: "Android" },
  { brand: "Stonex", model: "Stonex One", os: "Android" },
  { brand: "Turkcell", model: "T11", os: "Android" },
  { brand: "Turkcell", model: "T40", os: "Android" },
  { brand: "Xiaomi", model: "MI 2a", os: "Android" },
  { brand: "Xiaomi", model: "Mi 3", os: "Android" },
  { brand: "Xiaomi", model: "Mi 4", os: "Android" },
  { brand: "Xiaomi", model: "Mi 5", os: "Android" },
  { brand: "Xiaomi", model: "Mi 5s", os: "Android" },
  { brand: "Xiaomi", model: "Mi 5s Plus", os: "Android" },
  { brand: "Xiaomi", model: "Mi 5X", os: "Android" },
  { brand: "Xiaomi", model: "Mi 6", os: "Android" },
  { brand: "Xiaomi", model: "Mi 8", os: "Android" },
  { brand: "Xiaomi", model: "Mi Mix", os: "Android" },
  { brand: "Xiaomi", model: "Mi Mix 2", os: "Android" },
  { brand: "Xiaomi", model: "Mi Mix 2S", os: "Android" },
  { brand: "Xiaomi", model: "Mi Mix 3", os: "Android" },
  { brand: "Xiaomi", model: "Mi Note 2", os: "Android" },
  { brand: "Xiaomi", model: "Mi Note 3", os: "Android" },
];


export const testimonialData = [
  {
    name: "John Doe",
    rating: 5,
    feedback: "The NFC Business Cards are simply the best! The quality is outstanding, and the price is fair. Highly recommended."
  },
  {
    name: "Jane Smith",
    rating: 4.5,
    feedback: "I'm very impressed with the NFC Business Cards. They offer great value for the price and have a premium feel."
  },
  {
    name: "Michael Johnson",
    rating: 4,
    feedback: "Good quality and reasonable pricing. The NFC cards are a game changer for my business networking."
  },
  {
    name: "Emily Davis",
    rating: 5,
    feedback: "Fantastic product! The NFC cards are high-quality and the price is unbeatable. I love how easy they are to use."
  },
  {
    name: "David Martinez",
    rating: 4.8,
    feedback: "These NFC cards are top-notch. They offer excellent functionality and the price is very fair for what you get."
  },
  {
    name: "Sophia Lee",
    rating: 4.7,
    feedback: "Great value for money! The NFC cards are durable, look professional, and are priced just right."
  },
  {
    name: "James Wilson",
    rating: 4.9,
    feedback: "The NFC Business Cards exceeded my expectations. They are sleek, easy to use, and the price is very reasonable."
  },
  {
    name: "Olivia Brown",
    rating: 5,
    feedback: "Absolutely love these NFC cards! The quality is exceptional, and they're worth every penny."
  },
  {
    name: "William Green",
    rating: 4.6,
    feedback: "These NFC cards are fantastic! The pricing is fair, and they add a modern touch to my business interactions."
  },
  {
    name: "Ava Turner",
    rating: 4.5,
    feedback: "Excellent quality and fair pricing. The NFC cards are a must-have for anyone looking to make a great first impression."
  },
  {
    name: "Liam Thompson",
    rating: 5,
    feedback: "The NFC Business Cards are outstanding! The quality is premium, and the price is just right. Couldn't be happier."
  },
  {
    name: "Mia Anderson",
    rating: 4.3,
    feedback: "Good quality cards at a fair price. The NFC technology works flawlessly, making networking so much easier."
  },
  {
    name: "Ethan Clark",
    rating: 4.9,
    feedback: "These NFC cards are amazing! High quality and fairly priced. They have become an essential part of my business toolkit."
  },
  {
    name: "Charlotte Adams",
    rating: 4.4,
    feedback: "Very impressed with the NFC cards. They're durable, stylish, and the price is just right."
  },
  {
    name: "Henry Baker",
    rating: 4.8,
    feedback: "The NFC Business Cards are well worth the investment. The quality is great and the price is reasonable."
  }
];
